# Generated by Django 3.1.6 on 2021-05-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0003_horarioatencion'),
        ('actividadesAvaladas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAvaladaAsistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadAvalada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividadAvaladaAAA', to='actividadesAvaladas.actividadavalada')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoAAA', to='preregistro.medico')),
            ],
            options={
                'db_table': 'actividades_avaladas_asistentes',
                'ordering': ['-actividadAvalada'],
            },
        ),
    ]
