# Generated by Django 3.1.6 on 2021-05-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0002_actividadavaladaasistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='actividadAvalada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='actividadesAvaladas.actividadavalada'),
        ),
    ]
