# Generated by Django 3.1.6 on 2021-05-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0004_auto_20210520_1127'),
        ('actividadesAvaladas', '0004_actividadavalada_ispagado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadAvaladaAsistente',
            new_name='AsistenteActividadAvalada',
        ),
    ]
