# Generated by Django 3.1.6 on 2021-05-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0005_auto_20210520_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteactividadavalada',
            name='qrCodeImg',
            field=models.ImageField(blank=True, upload_to='qr-codes'),
        ),
    ]
