# Generated by Django 3.1.6 on 2021-05-27 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0006_asistenteactividadavalada_qrcodeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadavalada',
            name='archivo',
            field=models.FileField(blank=True, upload_to='actividadesAvaladas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='actividadavalada',
            name='banner',
            field=models.FileField(blank=True, upload_to='actividadesAvaladas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
    ]
