# Generated by Django 3.1.6 on 2021-05-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0007_auto_20210527_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadavalada',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='actividadavalada',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='actividadavalada',
            name='tipoPago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Precio por Médico')], db_column='tipo_pago'),
        ),
    ]
