# Generated by Django 3.1.6 on 2021-06-08 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0010_actividadavalada_qrcodeimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadavalada',
            name='fechaTermino',
            field=models.DateField(db_column='fecha_termino', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='actividadavalada',
            name='fechaInicio',
            field=models.DateField(db_column='fecha_inicio', default=datetime.date.today),
        ),
    ]
