# Generated by Django 3.1.6 on 2021-06-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0011_auto_20210608_1354'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asistenteactividadavalada',
            constraint=models.UniqueConstraint(fields=('medico', 'actividadAvalada'), name='unicoMedicoPorActiAvala'),
        ),
    ]
