# Generated by Django 3.1.6 on 2021-06-18 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0003_auto_20210527_1510'),
        ('actividadesAvaladas', '0012_auto_20210609_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadavalada',
            name='item',
        ),
        migrations.RemoveField(
            model_name='actividadavalada',
            name='numAsistentes',
        ),
        migrations.RemoveField(
            model_name='actividadavalada',
            name='puntosAsignar',
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='codigoWeb',
            field=models.CharField(blank=True, db_column='codigo_web', max_length=11),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='fechaLimite',
            field=models.DateField(db_column='fecha_limite', default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='itemAsistente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemAsistente', to='recertificacion.item'),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='itemCoordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemCoordinador', to='recertificacion.item'),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='itemPonente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemPonente', to='recertificacion.item'),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='puntajeAsistente',
            field=models.DecimalField(db_column='puntaje_asistente', decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='puntajeCoordinador',
            field=models.DecimalField(db_column='puntaje_coordinador', decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='actividadavalada',
            name='puntajePonente',
            field=models.DecimalField(db_column='puntaje_ponente', decimal_places=2, default=0, max_digits=6),
        ),
    ]
