# Generated by Django 3.1.6 on 2021-06-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0013_auto_20210618_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenteactividadavalada',
            name='isPagado',
            field=models.BooleanField(db_column='is_pagado', default=False),
        ),
        migrations.AddField(
            model_name='asistenteactividadavalada',
            name='tipo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
