# Generated by Django 3.1.6 on 2021-06-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesAvaladas', '0014_auto_20210621_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadavalada',
            name='tipoPago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Porcentaje'), (2, 'Precio')], db_column='tipo_pago'),
        ),
    ]
