# Generated by Django 3.1.6 on 2021-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=25)),
                ('mensaje', models.CharField(blank=True, max_length=50)),
                ('destinatario', models.IntegerField(blank=True, null=True)),
                ('remitente', models.IntegerField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-creado_en'],
            },
        ),
    ]
