# Generated by Django 3.1.6 on 2021-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
