# Generated by Django 3.1.5 on 2021-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='remitente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
