# Generated by Django 3.1.6 on 2021-05-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_auto_20210514_1255'),
        ('comunicados', '0002_auto_20210512_0910'),
    ]

    operations = [
    ]
