# Generated by Django 3.1.6 on 2021-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0003_merge_20210519_0912'),
        ('comunicados', '0003_auto_20210527_1510'),
    ]

    operations = [
    ]
