# Generated by Django 3.1.6 on 2021-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionFront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField()),
                ('user', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'posicion_front',
            },
        ),
        migrations.AddConstraint(
            model_name='posicionfront',
            constraint=models.UniqueConstraint(fields=('posicion', 'user'), name='posicion_user'),
        ),
    ]
