# Generated by Django 3.1.6 on 2021-04-30 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatMotivosRechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Validación'), (2, 'Engargolado')])),
            ],
            options={
                'db_table': 'cat_motivos_rechazo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='CatPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Examen Certificación Vigente'), (2, 'Examen Convocatoria Nacional'), (3, 'Examen Convocatoria Extranjero'), (4, 'Curso'), (5, 'Actividad Asistencial'), (6, 'Renovación de Certificación')], unique=True)),
            ],
            options={
                'db_table': 'cat_pagos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='CatSedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])])),
            ],
            options={
                'db_table': 'cat_sedes',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='CatTiposDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cat_tipos_documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='CatTiposExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('precioExtrangero', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'cat_tipos_examen',
                'ordering': ['descripcion'],
            },
        ),
    ]
