# Generated by Django 3.1.6 on 2021-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catpagos',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Examen Certificación Vigente'), (2, 'Examen Convocatoria Nacional'), (3, 'Examen Convocatoria Extranjero'), (4, 'Curso'), (5, 'Actividad Asistencial'), (6, 'Renovación de Certificación')]),
        ),
    ]
