# Generated by Django 3.1.6 on 2021-05-27 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20210510_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catpagos',
            options={'ordering': ['descripcion']},
        ),
        migrations.RemoveField(
            model_name='catpagos',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='catsedes',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='catalogos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
    ]
