# Generated by Django 3.1.6 on 2021-02-16 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_catsedes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsedes',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
    ]
