# Generated by Django 3.1.6 on 2021-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_cattiposexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatMotivosRechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Validación'), (2, 'Engargolado')])),
            ],
            options={
                'db_table': 'cat_motivos_rechazo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='CatTiposDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cat_tipos_documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='cattiposexamen',
            options={'ordering': ['descripcion']},
        ),
    ]
