# Generated by Django 3.1.6 on 2021-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_auto_20210218_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattiposexamen',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='cattiposexamen',
            name='precioExtrangero',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
