# Generated by Django 3.1.6 on 2021-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20210225_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Examen Certificación Vigente'), (2, 'Examen Convocatoria Nacional'), (3, 'Examen Convocatoria Extranjero'), (4, 'Curso'), (5, 'Actividad Asistencial'), (6, 'Renovación de Certificacion')])),
            ],
            options={
                'db_table': 'cat_pagos',
                'ordering': ['tipo'],
            },
        ),
    ]
