# Generated by Django 3.1.6 on 2021-11-09 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preregistro', '0016_medico_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conacem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fechaEnvio', models.DateField(db_column='fecha_envio', default=datetime.date.today)),
                ('tituloPresidente', models.CharField(db_column='titulo_presidente', max_length=10)),
                ('nombrePresidente', models.CharField(db_column='nombre_presidente', max_length=10)),
                ('tituloResponsable', models.CharField(db_column='titulo_responsable', max_length=10)),
                ('nombreResponsable', models.CharField(db_column='nombre_responsable', max_length=10)),
                ('fechaEmision', models.DateField(db_column='fecha_emision', default=datetime.date.today)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('fechaValidezDel', models.DateField(db_column='fecha_validez_del', default=datetime.date.today)),
                ('fechaValidezAl', models.DateField(db_column='fecha_validez_al', default=datetime.date.today)),
                ('iniciaLibro', models.PositiveSmallIntegerField(db_column='inicia_libro')),
                ('hoja', models.PositiveSmallIntegerField(db_column='hoja')),
                ('lugar', models.PositiveSmallIntegerField(db_column='lugar')),
                ('cupo', models.PositiveSmallIntegerField(db_column='cupo')),
            ],
            options={
                'db_table': 'conacem',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleConcacem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('libro', models.PositiveSmallIntegerField(blank=True, db_column='libro', null=True)),
                ('foja', models.PositiveSmallIntegerField(blank=True, db_column='foja', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('conacem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conacem', to='conacem.conacem')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='preregistro.medico')),
            ],
            options={
                'db_table': 'detalles_conacem',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
