# Generated by Django 3.1.6 on 2021-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conacem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleconcacem',
            old_name='medico',
            new_name='medicos',
        ),
        migrations.AlterField(
            model_name='conacem',
            name='nombrePresidente',
            field=models.CharField(db_column='nombre_presidente', max_length=200),
        ),
        migrations.AlterField(
            model_name='conacem',
            name='nombreResponsable',
            field=models.CharField(db_column='nombre_responsable', max_length=200),
        ),
    ]
