# Generated by Django 3.1.6 on 2021-11-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conacem', '0002_auto_20211108_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleconcacem',
            old_name='medicos',
            new_name='medico',
        ),
    ]
