# Generated by Django 3.1.6 on 2021-11-09 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0016_medico_titulo'),
        ('conacem', '0003_auto_20211108_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleconcacem',
            name='conacem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='conacem.conacem'),
        ),
        migrations.AlterField(
            model_name='detalleconcacem',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='preregistro.medico'),
        ),
    ]
