# Generated by Django 3.1.6 on 2021-12-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conacem', '0004_auto_20211108_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleconcacem',
            name='numCertificado',
            field=models.PositiveBigIntegerField(blank=True, db_column='numero_certificado', null=True),
        ),
    ]
