# Generated by Django 3.1.6 on 2021-12-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conacem', '0005_detalleconcacem_numcertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conacem',
            name='isCompletado',
            field=models.BooleanField(db_column='is_completado', default=False),
        ),
    ]
