# Generated by Django 3.1.6 on 2022-02-17 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preregistro', '0017_auto_20211220_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preregistro.medico')),
            ],
            options={
                'db_table': 'carpetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivosCarpetas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif', 'jpeg'])])),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivosCarpetas.carpeta')),
            ],
            options={
                'db_table': 'archivos',
                'ordering': ['nombre'],
            },
        ),
    ]
