# Generated by Django 3.1.6 on 2021-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('destinatario', models.IntegerField()),
            ],
            options={
                'db_table': 'conversacion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=300)),
                ('destinatario', models.IntegerField()),
                ('remitente', models.IntegerField()),
            ],
            options={
                'db_table': 'mensaje',
                'ordering': ['-creado_en'],
            },
        ),
    ]
