# Generated by Django 3.1.5 on 2021-01-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacion',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='actualzado_en',
        ),
    ]
