# Generated by Django 3.1.6 on 2021-11-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_auto_20210706_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='isConacem',
            field=models.BooleanField(db_column='is_tramite_concaem', default=False),
        ),
    ]
