# Generated by Django 3.1.6 on 2021-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_auto_20210527_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
