# Generated by Django 3.1.6 on 2021-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_auto_20210625_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numeroPago',
            field=models.PositiveSmallIntegerField(db_column='numero_pago', default=1),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
