# Generated by Django 3.1.6 on 2021-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('abreviatura', models.CharField(max_length=10)),
                ('solicitarReferencia', models.BooleanField(default=False)),
                ('inactivo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'formaPago',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('decimales', models.IntegerField()),
                ('porcentajeVariacion', models.CharField(max_length=10)),
                ('orden', models.IntegerField()),
                ('inactivo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('formatoCodigoPostal', models.CharField(max_length=100)),
                ('formatoRIT', models.CharField(max_length=100)),
                ('validacionRIT', models.CharField(max_length=100)),
                ('agrupacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadMedida', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('nota', models.CharField(max_length=300)),
                ('simbolo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'unidadMedida',
            },
        ),
        migrations.CreateModel(
            name='UsoCFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usoCFDI', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('personaFisica', models.BooleanField(default=False)),
                ('personaMoral', models.BooleanField(default=False)),
                ('orden', models.IntegerField()),
                ('inactivo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usoCFDI',
            },
        ),
    ]
