# Generated by Django 3.1.6 on 2021-06-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formapago',
            table='facturacionFormaPago',
        ),
        migrations.AlterModelTable(
            name='moneda',
            table='facturacionMoneda',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='facturacionPais',
        ),
        migrations.AlterModelTable(
            name='unidadmedida',
            table='facturacionUnidadMedida',
        ),
        migrations.AlterModelTable(
            name='usocfdi',
            table='facturacionUsoCFDI',
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptoPago', models.CharField(max_length=300)),
                ('precio', models.IntegerField(null=True)),
                ('inactivo', models.BooleanField(default=False)),
                ('claveSAT', models.CharField(max_length=50)),
                ('unidadMedida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida')),
            ],
            options={
                'db_table': 'facturacionConceptoPago',
            },
        ),
    ]
