# Generated by Django 3.1.6 on 2021-08-03 15:33

from django.db import migrations, models
import django.db.models.deletion
import facturacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0007_medico_iscertificado'),
        ('instituciones', '0002_institucion_username'),
        ('facturacion', '0003_moneda_tipocambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptopago',
            name='unidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.unidadmedida'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('codigoPostal', models.CharField(max_length=150)),
                ('comentarios', models.CharField(blank=True, max_length=250, null=True)),
                ('folio', models.CharField(max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=6, max_digits=21, null=True)),
                ('iva', models.DecimalField(decimal_places=6, max_digits=21, null=True)),
                ('total', models.DecimalField(decimal_places=6, max_digits=21, null=True)),
                ('uuid', models.CharField(max_length=50, null=True)),
                ('cadenaOriginal', models.TextField(null=True)),
                ('numeroCertificado', models.CharField(max_length=50, null=True)),
                ('numeroCertificadoSAT', models.CharField(max_length=50, null=True)),
                ('selloSAT', models.TextField(null=True)),
                ('selloCFDI', models.TextField(null=True)),
                ('fechaTimbrado', models.DateTimeField(null=True)),
                ('fechaCancelado', models.DateTimeField(null=True)),
                ('xmlTimbrado', models.FileField(null=True, upload_to=facturacion.models.rutaTimbrado)),
                ('xmlCancelado', models.FileField(null=True, upload_to=facturacion.models.rutaCancelado)),
                ('pdf', models.CharField(max_length=500, null=True)),
                ('formaPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.formapago')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituciones.institucion')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preregistro.medico')),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.moneda')),
                ('usoCFDI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.usocfdi')),
            ],
            options={
                'db_table': 'facturacionFactura',
            },
        ),
    ]
