# Generated by Django 3.1.6 on 2021-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20210803_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='calle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='colonia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='deleMuni',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numExterior',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numInterior',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='razonSocial',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='rfc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='codigoPostal',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
