# Generated by Django 3.1.6 on 2021-08-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_auto_20210810_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numRegIdTrib',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pais'),
        ),
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('conceptoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.conceptopago')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
            options={
                'db_table': 'facturacionConceptoFactura',
            },
        ),
    ]
