# Generated by Django 3.1.6 on 2021-12-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_auto_20210825_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numRegIdTrib',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
