# Generated by Django 3.1.6 on 2021-12-28 18:12

import datetime
from django.db import migrations, models
import django.utils.timezone
import facturacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_auto_20211223_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='hora',
            field=models.TimeField(db_column='hora_factura', default=facturacion.models.hora),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('Residente', 'Residente'), ('Certificado', 'Certificado'), ('Aval', 'Aval')], default='---', max_length=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(db_column='fecha_factura', default=datetime.date.today),
        ),
    ]
