# Generated by Django 3.1.6 on 2021-12-28 18:46

import datetime
from django.db import migrations, models
import facturacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_auto_20211228_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(blank=True, db_column='fecha_factura', default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='hora',
            field=models.TimeField(blank=True, db_column='hora_factura', default=facturacion.models.hora, null=True),
        ),
    ]
