# Generated by Django 3.1.6 on 2021-12-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_auto_20211228_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-actualizado_en']},
        ),
    ]
