# Generated by Django 3.1.6 on 2021-12-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_auto_20211229_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptofactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturaCF', to='facturacion.factura'),
        ),
    ]
