# Generated by Django 3.1.6 on 2021-12-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_auto_20211229_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='isCancelada',
            field=models.BooleanField(db_column='is_cancelada', default=False),
        ),
    ]
