# Generated by Django 3.1.6 on 2021-12-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_factura_iscancelada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'facturacionMetodoPago',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='metodoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.metodopago'),
        ),
    ]
