# Generated by Django 3.1.6 on 2022-01-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_auto_20211229_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
