# Generated by Django 3.1.6 on 2022-01-06 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_auto_20220104_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(blank=True, db_column='fecha_factura', default=datetime.date.today, null=True),
        ),
    ]
