# Generated by Django 3.1.6 on 2022-01-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20220106_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='hora',
        ),
    ]
