# Generated by Django 3.1.6 on 2022-01-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_remove_factura_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptopago',
            name='isAval',
            field=models.BooleanField(db_column='is_aval', default=True),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='isCertificado',
            field=models.BooleanField(db_column='is_certificado', default=True),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='isResidente',
            field=models.BooleanField(db_column='is_residente', default=True),
        ),
    ]
