# Generated by Django 3.1.6 on 2022-01-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_auto_20220113_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='anioFin',
            field=models.CharField(blank=True, db_column='anio_fin', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='anioInicio',
            field=models.CharField(blank=True, db_column='anio_inicio', default='', max_length=10),
        ),
    ]
