# Generated by Django 3.1.5 on 2021-01-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(db_column='ap_paterno', max_length=100)),
                ('apMaterno', models.CharField(db_column='ap_materno', max_length=100)),
                ('rfc', models.CharField(max_length=15)),
                ('curp', models.CharField(max_length=20)),
                ('fechaNac', models.DateField(db_column='fecha_nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='---', max_length=5)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('deleMuni', models.CharField(db_column='delegacion_municipio', max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('numInterior', models.CharField(db_column='num_exterior', max_length=10)),
                ('rfcFacturacion', models.CharField(db_column='rfc_facturacion', max_length=15)),
                ('usoCfdi', models.CharField(choices=[('GG', 'Gastos en General'), ('AM', 'Adlquisición de Mercancias'), ('PD', 'Por Definir')], db_column='uso_cfdi', default='PD', max_length=5)),
                ('paisConsult', models.CharField(blank=True, db_column='pais_consult', max_length=100)),
                ('estadoConsult', models.CharField(blank=True, db_column='estado_consult', max_length=100)),
                ('ciudadConsult', models.CharField(blank=True, db_column='ciudad_consult', max_length=100)),
                ('deleMuniConsult', models.CharField(blank=True, db_column='delegacion_municipio_consult', max_length=100)),
                ('coloniaConsult', models.CharField(blank=True, db_column='colonia_consult', max_length=100)),
                ('calleConsult', models.CharField(blank=True, db_column='calle_consult', max_length=100)),
                ('cpConsult', models.CharField(blank=True, db_column='cp_consult', max_length=10)),
                ('numInteriorConsult', models.CharField(blank=True, db_column='num_exterior_consult', max_length=10)),
                ('cedProfesional', models.CharField(db_column='ced_profesional', max_length=20)),
                ('cedEspecialidad', models.CharField(db_column='ced_especialidad', max_length=20)),
                ('cedCirugiaGral', models.CharField(db_column='ced_cirugia_gral', max_length=20)),
                ('hospitalResi', models.CharField(db_column='hospital_residencia', max_length=150)),
                ('telJefEnse', models.CharField(db_column='tel_jefatura_ense', max_length=15)),
                ('fechaInicioResi', models.DateField(db_column='fecha_inicio_residencia')),
                ('fechaFinResi', models.DateField(db_column='fecha_fin_residencia')),
                ('telCelular', models.CharField(db_column='tel_celular', max_length=15)),
                ('telParticular', models.CharField(db_column='tel_particular', max_length=15)),
                ('telConsultorio', models.CharField(blank=True, db_column='tel_consultorio', max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('emailAlterno', models.CharField(blank=True, db_column='email_alterno', max_length=50)),
                ('aceptado', models.BooleanField(default=False)),
                ('motivo', models.TextField(blank=True)),
                ('numRegistro', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'pre_registro_medico',
                'ordering': ['creado_en'],
            },
        ),
    ]
