# Generated by Django 3.1.5 on 2021-01-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0002_auto_20210107_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['-creado_en']},
        ),
    ]
