# Generated by Django 3.1.6 on 2021-05-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0002_auto_20210514_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15)),
                ('horaInicio', models.CharField(blank=True, db_column='hora_inicio', max_length=10)),
                ('horaTermino', models.CharField(blank=True, db_column='hora_termino', max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoHA', to='preregistro.medico')),
            ],
            options={
                'db_table': 'horario_atencion',
                'ordering': ['-medico'],
            },
        ),
    ]
