# Generated by Django 3.1.5 on 2021-01-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0003_auto_20210108_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='usoCfdi',
            field=models.CharField(choices=[('G03', 'Gastos en General'), ('G01', 'Adlquisición de Mercancias'), ('P01', 'Por Definir')], db_column='uso_cfdi', default='P01', max_length=5),
        ),
    ]
