# Generated by Django 3.1.6 on 2021-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0003_horarioatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='telCelularPublico',
            field=models.CharField(blank=True, db_column='tel_celular_publico', max_length=15),
        ),
        migrations.AddField(
            model_name='medico',
            name='telConsultorioPublico',
            field=models.CharField(blank=True, db_column='tel_consultorio_publico', max_length=15),
        ),
    ]
