# Generated by Django 3.1.6 on 2021-05-27 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0004_auto_20210520_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fotoPerfil',
            field=models.FileField(blank=True, db_column='foto_perfil', null=True, upload_to='preregistro', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
    ]
