# Generated by Django 3.1.6 on 2021-02-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0004_auto_20210120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='usoCfdi',
            field=models.CharField(choices=[('G03', 'Gastos en General'), ('G01', 'Adquisición de Mercancías'), ('P01', 'Por Definir')], db_column='uso_cfdi', default='P01', max_length=5),
        ),
    ]
