# Generated by Django 3.1.6 on 2021-07-06 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0005_auto_20210527_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='fotoPerfil',
            field=models.FileField(blank=True, db_column='foto_perfil', null=True, upload_to='preregistro', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg'])]),
        ),
    ]
