# Generated by Django 3.1.6 on 2021-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0006_auto_20210204_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
