# Generated by Django 3.1.6 on 2021-02-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0007_medico_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='isExtrangero',
            field=models.BooleanField(db_column='is_extrangero', default=False),
        ),
        migrations.AddField(
            model_name='medico',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
