# Generated by Django 3.1.6 on 2021-08-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0007_medico_iscertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cedEspecialidad',
            field=models.CharField(blank=True, db_column='ced_especialidad', max_length=20),
        ),
    ]
