# Generated by Django 3.1.6 on 2021-08-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0008_auto_20210805_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='anioCertificacion',
            field=models.CharField(blank=True, db_column='anio_certificacion', max_length=9),
        ),
        migrations.AddField(
            model_name='medico',
            name='isConsejero',
            field=models.BooleanField(db_column='is_consejero', default=False),
        ),
        migrations.AddField(
            model_name='medico',
            name='isProfesor',
            field=models.BooleanField(db_column='is_profesor', default=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='isCertificado',
            field=models.BooleanField(db_column='is_certificado', default=False),
        ),
    ]
