# Generated by Django 3.1.6 on 2021-02-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0008_auto_20210210_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='isExtrangero',
        ),
        migrations.AddField(
            model_name='medico',
            name='isExtranjero',
            field=models.BooleanField(db_column='is_extranjero', default=False),
        ),
    ]
