# Generated by Django 3.1.6 on 2021-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0009_auto_20210811_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='anioCertificacion',
            field=models.PositiveSmallIntegerField(db_column='anio_certificacion', default=0),
        ),
    ]
