# Generated by Django 3.1.6 on 2021-04-01 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0010_auto_20210211_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='fotoPerfil',
            field=models.FileField(blank=True, db_column='foto_perfil', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='escuelaExtranjero',
            field=models.CharField(blank=True, db_column='escuela_extranjero', max_length=200),
        ),
        migrations.AlterField(
            model_name='medico',
            name='numRegistro',
            field=models.IntegerField(blank=True, db_column='num_registro', null=True),
        ),
    ]
