# Generated by Django 3.1.6 on 2021-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0011_auto_20210811_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='calleFisc',
            field=models.CharField(blank=True, db_column='calle_fiscal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='ciudadFisc',
            field=models.CharField(blank=True, db_column='ciudad_fiscal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='coloniaFisc',
            field=models.CharField(blank=True, db_column='colonia_fiscal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='cpFisc',
            field=models.CharField(blank=True, db_column='cp_fiscal', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='deleMuniFisc',
            field=models.CharField(blank=True, db_column='delegacion_municipio_fiscal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='estadoFisc',
            field=models.CharField(blank=True, db_column='estado_fiscal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='numExteriorFisc',
            field=models.CharField(blank=True, db_column='num_exterior_fiscal', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='numInteriorFisc',
            field=models.CharField(blank=True, db_column='num_interior_fiscal', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='paisFisc',
            field=models.CharField(blank=True, db_column='pais_fiscal', max_length=100, null=True),
        ),
    ]
