# Generated by Django 3.1.6 on 2021-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0012_auto_20210824_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='regionGeografica',
            field=models.CharField(blank=True, db_column='region_geografica', max_length=300),
        ),
    ]
