# Generated by Django 3.1.6 on 2021-11-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0014_medico_tipoaspirante'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='codigoCarta',
            field=models.CharField(blank=True, db_column='codigo_carta_cmcper', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='notasObser',
            field=models.TextField(blank=True, db_column='notas_observaciones', null=True),
        ),
    ]
