# Generated by Django 3.1.6 on 2021-12-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0016_medico_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='notasObser',
        ),
        migrations.CreateModel(
            name='NotasObservaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('isBorrado', models.BooleanField(db_column='is_borrado', default=False)),
                ('tipo', models.CharField(choices=[('Nota', 'Nota'), ('Observacion', 'Observacion')], default='Nota', max_length=15)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoNO', to='preregistro.medico')),
            ],
            options={
                'db_table': 'preregistro_notas_observaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
