# Generated by Django 3.1.6 on 2021-04-30 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('preregistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isOpcional', models.BooleanField(db_column='is_opcional', default=False)),
                ('icono', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
            ],
            options={
                'db_table': 'capitulos',
                'ordering': ['-titulo'],
            },
        ),
        migrations.CreateModel(
            name='FechasExamenRecertificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fechaExamen', models.DateField(db_column='fecha_examen')),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'fechas_examen_recertificacion',
                'ordering': ['-fechaExamen'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['subcapitulo'],
            },
        ),
        migrations.CreateModel(
            name='PorExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estatus', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Pendiente')])),
                ('isAprobado', models.BooleanField(db_column='is_aprobado', default=False)),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isPagado', models.BooleanField(db_column='is_pagado', default=False)),
                ('isAceptado', models.BooleanField(db_column='is_aceptado', default=False)),
                ('isPublicado', models.BooleanField(db_column='is_publicado', default=False)),
                ('fechaExamen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechaExamenPE', to='recertificacion.fechasexamenrecertificacion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoPE', to='preregistro.medico')),
            ],
            options={
                'db_table': 'recertificacion_por_examen',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Subcapitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capituloS', to='recertificacion.capitulo')),
            ],
            options={
                'db_table': 'subcapitulos',
                'ordering': ['capitulo'],
            },
        ),
        migrations.CreateModel(
            name='RecertificacionItemDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('tituloDescripcion', models.CharField(db_column='titulo_descripcion', max_length=300)),
                ('fechaEmision', models.DateField(db_column='fecha_emision')),
                ('puntosOtorgados', models.DecimalField(db_column='puntos_otorgados', decimal_places=2, max_digits=6)),
                ('estatus', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Pendiente')])),
                ('observaciones', models.TextField(blank=True, db_column='observaciones')),
                ('notasRechazo', models.TextField(blank=True, db_column='notas_rechzo')),
                ('razonRechazo', models.CharField(blank=True, db_column='razon_rechazo', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemRID', to='recertificacion.item')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoRID', to='preregistro.medico')),
            ],
            options={
                'db_table': 'recertificacion_item_documentos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='PorExamenDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('isAceptado', models.BooleanField(db_column='is_aceptado', default=False)),
                ('catTiposDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catTiposDocumentoPED', to='catalogos.cattiposdocumento')),
                ('porExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porExamenD', to='recertificacion.porexamen')),
            ],
            options={
                'db_table': 'recertificacion_por_examen_documentos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcapitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcapituloI', to='recertificacion.subcapitulo'),
        ),
    ]
