# Generated by Django 3.1.6 on 2021-04-02 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=300)),
                ('puntos', models.PositiveSmallIntegerField()),
                ('maximo', models.PositiveSmallIntegerField()),
                ('minimo', models.PositiveSmallIntegerField()),
                ('isOpcional', models.BooleanField(db_column='is_opcional', default=False)),
                ('icono', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
            ],
            options={
                'db_table': 'capitulos',
                'ordering': ['-titulo'],
            },
        ),
        migrations.CreateModel(
            name='Subcapitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('comentarios', models.TextField(blank=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcapituloC', to='recertificacion.capitulo')),
            ],
            options={
                'db_table': 'subcapitulos',
                'ordering': ['capitulo'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('puntos', models.PositiveSmallIntegerField()),
                ('subcapitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemS', to='recertificacion.subcapitulo')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['subcapitulo'],
            },
        ),
    ]
