# Generated by Django 3.1.6 on 2021-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcapitulo',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
