# Generated by Django 3.1.6 on 2021-05-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0001_initial'),
        ('recertificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('isPagado', models.BooleanField(db_column='is_pagado', default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoR', to='preregistro.medico')),
            ],
            options={
                'db_table': 'recertificacion_renovaciones',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
