# Generated by Django 3.1.6 on 2021-05-27 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0002_renovacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='recertificacion', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='porexamendocumento',
            name='documento',
            field=models.FileField(blank=True, upload_to='recertificacion', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='recertificacionitemdocumento',
            name='documento',
            field=models.FileField(blank=True, upload_to='recertificacion', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])]),
        ),
    ]
