# Generated by Django 3.1.6 on 2021-04-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0002_auto_20210402_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='puntos',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
