# Generated by Django 3.1.6 on 2021-04-05 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20210225_1043'),
        ('preregistro', '0011_auto_20210401_0918'),
        ('recertificacion', '0004_auto_20210405_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecertificacionDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('isValidado', models.BooleanField(db_column='is_validado', default=False)),
                ('notasValidado', models.TextField(blank=True, db_column='notas_validado')),
                ('rechazoValidado', models.CharField(blank=True, db_column='rechazo_validado', max_length=200)),
                ('catTiposDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catTiposDocumentoR', to='catalogos.cattiposdocumento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoR', to='preregistro.medico')),
            ],
            options={
                'db_table': 'recertificacion_documentos',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
