# Generated by Django 3.1.6 on 2021-04-05 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20210225_1043'),
        ('preregistro', '0011_auto_20210401_0918'),
        ('recertificacion', '0005_recertificaciondocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('descripcion', models.CharField(max_length=300)),
                ('isVencido', models.BooleanField(db_column='is_vencido', default=False)),
                ('anioInicio', models.SmallIntegerField(db_column='anio_inicio')),
                ('catTiposDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catTiposDocumentoC', to='catalogos.cattiposdocumento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoC', to='preregistro.medico')),
            ],
            options={
                'db_table': 'certificados',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
