# Generated by Django 3.1.6 on 2021-04-05 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20210225_1043'),
        ('preregistro', '0011_auto_20210401_0918'),
        ('recertificacion', '0006_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estatus', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Pendiente')])),
                ('isAprobado', models.BooleanField(db_column='is_aprobado', default=False)),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoPE', to='preregistro.medico')),
            ],
            options={
                'db_table': 'recertificacion_por_examen',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='PorExamenDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('isAceptado', models.BooleanField(db_column='is_aceptado', default=False)),
                ('catTiposDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catTiposDocumentoPED', to='catalogos.cattiposdocumento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoPED', to='preregistro.medico')),
                ('porExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porExamenD', to='recertificacion.porexamen')),
            ],
            options={
                'db_table': 'recertificacion_por_examen_documentos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='RecertificacionItemDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('tituloDescripcion', models.CharField(db_column='titulo_descripcion', max_length=300)),
                ('fechaEmision', models.DateField(db_column='fecha_emision')),
                ('puntosOtorgados', models.DecimalField(db_column='puntos_otorgados', decimal_places=2, max_digits=6)),
                ('estatus', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Pendiente')])),
                ('observaciones', models.TextField(blank=True, db_column='observaciones')),
                ('notasRechazo', models.TextField(blank=True, db_column='notas_rechzo')),
                ('razonRechazo', models.CharField(blank=True, db_column='razon_rechazo', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='subcapitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcapituloI', to='recertificacion.subcapitulo'),
        ),
        migrations.AlterField(
            model_name='subcapitulo',
            name='capitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capituloS', to='recertificacion.capitulo'),
        ),
        migrations.DeleteModel(
            name='RecertificacionDocumento',
        ),
        migrations.AddField(
            model_name='recertificacionitemdocumento',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemRID', to='recertificacion.item'),
        ),
        migrations.AddField(
            model_name='recertificacionitemdocumento',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoRID', to='preregistro.medico'),
        ),
    ]
