# Generated by Django 3.1.6 on 2022-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0007_recertificacionitemdocumento_actividadavaladaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='isActivo',
            field=models.BooleanField(db_column='is_activo', default=True),
        ),
    ]
