# Generated by Django 3.1.6 on 2021-04-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0007_auto_20210405_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porexamendocumento',
            name='medico',
        ),
    ]
