# Generated by Django 3.1.6 on 2021-04-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0008_remove_porexamendocumento_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recertificacionitemdocumento',
            options={'ordering': ['-actualizado_en']},
        ),
        migrations.AlterModelTable(
            name='recertificacionitemdocumento',
            table='recertificacion_item_documentos',
        ),
    ]
