# Generated by Django 3.1.6 on 2022-01-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0008_capitulo_isactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isActivo',
            field=models.BooleanField(db_column='is_activo', default=True),
        ),
        migrations.AddField(
            model_name='subcapitulo',
            name='isActivo',
            field=models.BooleanField(db_column='is_activo', default=True),
        ),
    ]
