# Generated by Django 3.1.6 on 2021-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0010_remove_certificado_cattiposdocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='anioInicio',
        ),
        migrations.AddField(
            model_name='certificado',
            name='anioCertificacion',
            field=models.SmallIntegerField(db_column='anio_certificacion', default=0),
        ),
    ]
