# Generated by Django 3.1.6 on 2021-04-07 01:44

import datetime
from django.db import migrations, models
import recertificacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0011_auto_20210405_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='anioCertificacion',
        ),
        migrations.AddField(
            model_name='certificado',
            name='estatus',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vigente'), (2, 'Esta por Vencer'), (3, 'Vencido')], default=1),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fechaCaducidad',
            field=models.DateField(db_column='fecha_caducidad', default=recertificacion.models.caducidad),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fechaCertificacion',
            field=models.DateField(db_column='fecha_certificacion', default=datetime.date.today),
        ),
    ]
