# Generated by Django 3.1.6 on 2021-04-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0012_auto_20210406_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasExamenRecertificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fechaExamen', models.DateField(db_column='fecha_examen')),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'fechas_examen_recertificacion',
                'ordering': ['-fechaExamen'],
            },
        ),
    ]
