# Generated by Django 3.1.6 on 2021-04-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0013_fechasexamenrecertificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='porexamen',
            name='isAceptado',
            field=models.BooleanField(db_column='is_aceptado', default=False),
        ),
        migrations.AddField(
            model_name='porexamen',
            name='isPagado',
            field=models.BooleanField(db_column='is_pagado', default=False),
        ),
    ]
