# Generated by Django 3.1.6 on 2021-04-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0014_auto_20210422_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='porexamen',
            name='fechaExamen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fechaExamenPE', to='recertificacion.fechasexamenrecertificacion'),
        ),
    ]
