# Generated by Django 3.1.6 on 2021-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recertificacion', '0015_porexamen_fechaexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='porexamen',
            name='isPublicado',
            field=models.BooleanField(db_column='is_publicado', default=False),
        ),
    ]
