# Generated by Django 3.1.6 on 2021-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombreInstitucion', models.CharField(db_column='nombre_institucion', max_length=150)),
                ('rfc', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=150)),
                ('telUno', models.CharField(db_column='tel_uno', max_length=15)),
                ('telDos', models.CharField(db_column='tel_dos', max_length=15)),
                ('telCelular', models.CharField(db_column='tel_celular', max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('deleMuni', models.CharField(db_column='delegacion_municipio', max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('numInterior', models.CharField(blank=True, db_column='num_interior', max_length=10)),
                ('numExterior', models.CharField(db_column='num_exterior', max_length=10)),
            ],
            options={
                'db_table': 'instituciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
