# Generated by Django 3.1.6 on 2021-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
