# Generated by Django 3.1.6 on 2021-04-30 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('preregistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fechaInicio', models.DateField(db_column='fecha_inicio')),
                ('fechaTermino', models.DateField(db_column='fecha_termino')),
                ('fechaExamen', models.DateField(db_column='fecha_examen')),
                ('horaExamen', models.TimeField(db_column='hora_examen')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('banner', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])])),
                ('detalles', models.TextField(blank=True)),
                ('fechaResolucion', models.DateField(blank=True, db_column='fecha_resolucion', null=True)),
            ],
            options={
                'db_table': 'convocatoria',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catTiposExamen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catTiposExamen', to='catalogos.cattiposexamen')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposExamen', to='convocatoria.convocatoria')),
            ],
            options={
                'db_table': 'tipo_examen',
                'ordering': ['-catTiposExamen'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catSedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catSedes', to='catalogos.catsedes')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='convocatoria.convocatoria')),
            ],
            options={
                'db_table': 'sede',
                'ordering': ['-catSedes'],
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaEnroladoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('isValidado', models.BooleanField(db_column='is_validado', default=False)),
                ('engargoladoOk', models.BooleanField(db_column='engargolado_ok', default=False)),
                ('notasValidado', models.TextField(blank=True, db_column='notas_validado')),
                ('notasEngargolado', models.TextField(blank=True, db_column='notas_engargolado')),
                ('rechazoValidado', models.CharField(blank=True, db_column='rechazo_validado', max_length=200)),
                ('rechazoEngargolado', models.CharField(blank=True, db_column='rechazo_engargolado', max_length=200)),
                ('catTiposDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catTiposDocumentoD', to='catalogos.cattiposdocumento')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoriaD', to='convocatoria.convocatoria')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoD', to='preregistro.medico')),
            ],
            options={
                'db_table': 'convocatorias_enrolados_documentos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaEnrolado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True)),
                ('isPagado', models.BooleanField(db_column='is_pagado', default=False)),
                ('isAceptado', models.BooleanField(db_column='is_aceptado', default=False)),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isAprobado', models.BooleanField(db_column='is_aprobado', default=False)),
                ('isPublicado', models.BooleanField(db_column='is_publicado', default=False)),
                ('catSedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catSedesE', to='catalogos.catsedes')),
                ('catTiposExamen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catTiposExamenE', to='catalogos.cattiposexamen')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoriaE', to='convocatoria.convocatoria')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoE', to='preregistro.medico')),
            ],
            options={
                'db_table': 'convocatorias_enrolados',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
