# Generated by Django 3.1.6 on 2021-02-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualzado_en', models.DateTimeField(auto_now=True)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('fechaExamen', models.DateField()),
                ('horaExamen', models.TimeField()),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='')),
                ('banner', models.FileField(upload_to='')),
                ('detalles', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoExamenes', to='convocatoria.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='convocatoria.convocatoria')),
            ],
        ),
    ]
