# Generated by Django 3.1.6 on 2021-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaExamen',
            field=models.DateField(db_column='fecha_examen'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaInicio',
            field=models.DateField(db_column='fecha_inicio'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaTermino',
            field=models.DateField(db_column='fecha_termino'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='horaExamen',
            field=models.TimeField(db_column='hora_examen'),
        ),
    ]
