# Generated by Django 3.1.6 on 2021-02-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_auto_20210211_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['-descripcion']},
        ),
        migrations.AlterModelOptions(
            name='tipoexamen',
            options={'ordering': ['-descripcion']},
        ),
        migrations.AlterModelTable(
            name='convocatoria',
            table='convocatoria',
        ),
        migrations.AlterModelTable(
            name='sede',
            table='sede',
        ),
        migrations.AlterModelTable(
            name='tipoexamen',
            table='tipo_examen',
        ),
    ]
