# Generated by Django 3.1.6 on 2021-02-11 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0003_auto_20210211_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='archivo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='banner',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
    ]
