# Generated by Django 3.1.6 on 2021-02-15 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0004_auto_20210211_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='archivo',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='banner',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='sede',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedesConvocatoria', to='convocatoria.convocatoria'),
        ),
    ]
