# Generated by Django 3.1.6 on 2021-02-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0005_auto_20210215_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='convocatoria.convocatoria'),
        ),
    ]
