# Generated by Django 3.1.6 on 2021-02-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_cattiposexamen'),
        ('preregistro', '0010_auto_20210211_1001'),
        ('convocatoria', '0007_auto_20210217_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocatoriaEnrolado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True)),
                ('isPagado', models.BooleanField(db_column='is_pagado', default=False)),
                ('isAceptado', models.BooleanField(db_column='is_aceptado', default=False)),
                ('catSedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catSedesE', to='catalogos.catsedes')),
                ('catTiposExamen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catTiposExamenE', to='catalogos.cattiposexamen')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoria', to='convocatoria.convocatoria')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='preregistro.medico')),
            ],
            options={
                'db_table': 'convocatorias_enrolados',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
