# Generated by Django 3.1.6 on 2021-02-18 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0010_auto_20210211_1001'),
        ('catalogos', '0005_auto_20210218_1216'),
        ('convocatoria', '0008_convocatoriaenrolado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoriaenrolado',
            name='convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoriaE', to='convocatoria.convocatoria'),
        ),
        migrations.AlterField(
            model_name='convocatoriaenrolado',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoE', to='preregistro.medico'),
        ),
        migrations.CreateModel(
            name='ConvocatoriaEnroladoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('isValidado', models.BooleanField(db_column='is_validado', default=False)),
                ('engargoladoOk', models.BooleanField(db_column='engargolado_ok', default=False)),
                ('notasValidado', models.TextField(blank=True, db_column='notas_validado')),
                ('notasEngargolado', models.TextField(blank=True, db_column='notas_engargolado')),
                ('rechazoValidado', models.CharField(blank=True, db_column='rechazo_validado', max_length=200)),
                ('rechazoEngargolado', models.CharField(blank=True, db_column='rechazo_engargolado', max_length=200)),
                ('catTiposDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catTiposExamenD', to='catalogos.cattiposdocumento')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoriaD', to='convocatoria.convocatoria')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoD', to='preregistro.medico')),
            ],
            options={
                'db_table': 'convocatorias_enrolados_documentos',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
