# Generated by Django 3.1.6 on 2021-03-09 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0011_remove_convocatoria_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriaenrolado',
            name='calificacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoriaenrolado',
            name='certificado',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])]),
        ),
    ]
