# Generated by Django 3.1.6 on 2021-03-11 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0010_auto_20210211_1001'),
        ('convocatoria', '0012_auto_20210309_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(blank=True, max_length=400)),
                ('comprobante', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif'])])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('nota', models.CharField(blank=True, max_length=400)),
                ('estatus', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'Pendiente')])),
                ('convocatoriaEnrolado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoriaEnroladoP', to='convocatoria.convocatoriaenrolado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoP', to='preregistro.medico')),
            ],
            options={
                'db_table': 'registros_pagos',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
