# Generated by Django 3.1.6 on 2021-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0013_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='fechaResolucion',
            field=models.DateField(blank=True, db_column='fecha_resolucion', null=True),
        ),
    ]
