# Generated by Django 3.1.6 on 2021-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0016_remove_convocatoriaenrolado_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriaenrolado',
            name='isPublicado',
            field=models.BooleanField(db_column='is_publicado', default=False),
        ),
    ]
