# Generated by Django 3.1.6 on 2021-04-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0017_convocatoriaenrolado_ispublicado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
