# Generated by Django 3.1.6 on 2022-01-17 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTiposDocumentoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cat_tipos_documento_entrega',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='EntregaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField(db_column='fecha_entrega')),
                ('nombreRecibe', models.CharField(db_column='nombre_quien_recibe', max_length=250)),
                ('libro', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('foja', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregaFisica', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'gif', 'jpeg'])])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('catTiposDocumentoEntrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catTiposDocumentoEntregaEF', to='entregaFisica.cattiposdocumentoentrega')),
            ],
            options={
                'db_table': 'entrega_fisica',
                'ordering': ['-creado_en'],
            },
        ),
    ]
