# Generated by Django 3.1.6 on 2022-01-17 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregaFisica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregafisica',
            name='fecha',
            field=models.DateField(db_column='fecha_entrega', default=datetime.date.today),
        ),
    ]
