# Generated by Django 3.1.6 on 2022-01-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0017_auto_20211220_1320'),
        ('entregaFisica', '0003_auto_20220117_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregafisica',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicoEF', to='preregistro.medico'),
        ),
    ]
