# Generated by Django 3.1.6 on 2022-01-20 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregaFisica', '0004_entregafisica_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattiposdocumentoentrega',
            name='isActivo',
            field=models.BooleanField(db_column='is_activo', default=True),
        ),
        migrations.AlterField(
            model_name='entregafisica',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='entregaFisica', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'gif', 'jpeg'])]),
        ),
    ]
