# Generated by Django 3.1.6 on 2022-01-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregaFisica', '0005_auto_20220120_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregafisica',
            name='anioFin',
            field=models.CharField(db_column='anio_fin', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entregafisica',
            name='anioInicio',
            field=models.CharField(db_column='anio_inicio', default='', max_length=10),
        ),
    ]
