# Generated by Django 3.1.6 on 2022-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='regionGeografica',
            field=models.CharField(blank=True, db_column='region_geografica', max_length=300, null=True),
        ),
    ]
